### ISSUE TITLE
Not supported on latest version of dio

### ISSUE THREAD

**Issue by uc-dve** [aloisdeniel/dio_retry#10]
Please resolve and release a new version ASAP.

> Because dio_retry >=0.1.9-beta depends on dio ^3.0.0 and ucertify_learn depends on dio ^4.0.0-beta4, dio_retry >=0.1.9-beta is forbidden.
> So, because ucertify_learn depends on dio_retry ^0.1.9-beta, version solving failed.

**Comment by azeek** [comment]
Thank Golapadeog

Until this plugin is officially updated, you can use it in the following ways.
```yaml
dependencies:
  dio_retry:
    git:
      url: https://github.com/Golapadeog/dio_retry.git 
      path: dio_retry
      ref: null-safety-migration
```
